name: CI/CD

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['10.x']
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack NuGet package
        if: matrix.os == 'ubuntu-latest'
        run: dotnet pack --no-build --configuration Release --output ./artifacts

      - name: Upload NuGet artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg

  deploy:
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: write
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update project version
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.version.outputs.VERSION }}<\/Version>/" TimeMcpServer.csproj
          sed -i 's/{{VERSION}}/${{ steps.version.outputs.VERSION }}/g' server.json

      - name: Pack
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Wait for NuGet package availability
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          MAX_ATTEMPTS=60
          SLEEP_SECONDS=10

          echo "Waiting for package to be indexed on NuGet..."
          for i in $(seq 1 $MAX_ATTEMPTS); do
            if curl -s -f "https://api.nuget.org/v3-flatcontainer/timemcpserver/$VERSION/readme" > /dev/null 2>&1; then
              echo "Package is now indexed on NuGet!"
              exit 0
            fi
            echo "Attempt $i/$MAX_ATTEMPTS: Package not yet indexed, waiting ${SLEEP_SECONDS}s..."
            sleep $SLEEP_SECONDS
          done

          echo "Package did not become indexed after $MAX_ATTEMPTS attempts"
          exit 1

      - name: Install mcp-publisher
        run: curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.0.0/mcp-publisher_1.0.0_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*.nupkg
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}